on:
  - push
  - workflow_dispatch
env:
  MVN_CACHE_FOLDER: lib/
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"
      - uses: actions/cache@v3
        with:
          path: ${{ env.MVN_CACHE_FOLDER }}
          key: ${{ hashFiles('pom.xml') }}
      - run: ./mvnw -Dmaven.repo.local=$MVN_CACHE_FOLDER help:evaluate -Dexpression=settings.localRepository -q -DforceStdout
      - run: ./mvnw -Dmaven.repo.local=$MVN_CACHE_FOLDER dependency:go-offline dependency:tree test -DskipTests
      - run: |
          find . -mindepth 1 -maxdepth 1 ! \( -name 'pom.xml' -o -name '.mvn' -o -name 'mvnw' -o -name 'eclipse-formatter.xml' -o -name 'spotless.xml.prefs' -o -name 'lib' \) -exec rm -r {} +
          ./mvnw -Dmaven.repo.local=$MVN_CACHE_FOLDER spotless:check
  deploy-aws-infra:
    runs-on: ubuntu-latest
    needs: setup
    env:
      DEPLOYMENT_TYPE: INFRA
    steps:
      - uses: actions/checkout@v3
        with:
          repository: hoquangnam45/pharmacy-infra
      - uses: ./actions/setup-deployment
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: actions/cache@v3
        with:
          path: ${{ env.MVN_CACHE_FOLDER }}
          key: ${{ hashFiles('pom.xml') }}
      - name: Update dependencies snapshot
        run: ./mvnw -Dmaven.repo.local=$MVN_CACHE_FOLDER dependency:go-offline dependency:tree test -DskipTests -U
      - run: ./mvnw -Dmaven.repo.local=$MVN_CACHE_FOLDER spotless:check -o
      - run: ./mvnw -Dmaven.repo.local=$MVN_CACHE_FOLDER test -o
      - run: npx cdk deploy --app "./mvnw -Dmaven.repo.local=$MVN_CACHE_FOLDER -e -q compile exec:java" --require-approval never
